### ISSUE TITLE
cuishark will crush if i resize the terminal window every time.

### ISSUE THREAD

**Issue by shawvi** [cuishark/cuishark#6]
- my system information:
4.8.0-54-generic #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- exception information
rminate called after throwing an instance of 'slankdev::exception' what():  poll

 thx

**Comment by slankdev** [comment]
#7 fix the crush when it resized the the terminal window.
Until now, I didn't support that behavior, @gtalis corresponded.
