### ISSUE TITLE
Does cuishark provided API?

### ISSUE THREAD

**Issue by kevinbird61** [cuishark/cuishark#9]
cuishark is a fancy work!

Does it have API support?
( Like add web service, or 3rd party application usage on it )

Thanks!

**Comment by slankdev** [comment]
Hi, Thx using cuishark.
Now, I don't have plan 'API support'. 
But, I plan to get compatibility to wireshark-dissectors via pyshark or direct-link libwireshark.

**Comment by kevinbird61** [comment]
Thank for reply!
I got your point.
